# Generated by Django 2.2 on 2020-06-04 13:28

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False
	dependencies = [
		('users', '0006_user_is_staff'),
		]

	operations = [
	migrations.AlterModelTable(
		name='user',
		table='users',
		),
	]
